export const STUDENT_FIELD_NAME = [
    {
        en:'studentCode',
        th:'รหัสประจำตัว'
    },
    {
        en:'studentNumber',
        th:'เลขที่'
    },
    {
        en:'personalCode',
        th:'รหัสบัตรประชาชน'
    },
    {
        en:'classroomTypeValue',
        th:'ชั้นเรียน'
    },
    {
        en:'classroomValue',
        th:'ห้อง'
    },
    {
        en:'classSpecial',
        th:'ห้องเรียนพิเศษ'
    },
    {
        en:'classSpecialText',
        th:'ห้องเรียนพิเศษอื่นๆ'
    },
    {
        en:'status',
        th:'สถานะ'
    },
    {
        en:'reasonResign',
        th:'เหตุผลการลาออก'
    },
    {
        en:'title',
        th:'คำนำหน้า'
    },
    {
        en:'titleEn',
        th:'คำนำหน้า(EN)'
    },
    {
        en:'firstname',
        th:'ชื่อจริง'
    },
    {
        en:'lastname',
        th:'นามสกุล'
    },
    {
        en:'firstnameEn',
        th:'ชื่อจริง(EN)'
    },
    {
        en:'lastnameEn',
        th:'นามสกุล(EN)'
    },
    {
        en:'gendarValue',
        th:'เพศ'
    },
    {
        en:'birthDate',
        th:'วันที่เกิด'
    },
    {
        en:'acceptDate',
        th:'วันมอบตัว'
    },
    {
        en:'nationalityValue',
        th:'สัญชาติ'
    },
    {
        en:'ethnicityValue',
        th:'เชื้อชาติ'
    },
    {
        en:'religionValue',
        th:'ศาสนา'
    },
    {
        en:'email',
        th:'ที่อยู่อีเมลล์'
    },
    {
        en:'phoneNumber',
        th:'เบอร์โทรศัพท์'
    },
    {
        en:'specialAbility',
        th:'ความสามารถพิเศษ'
    },
    {
        en:'birthHospital',
        th:'โรงพยาบาล'
    },
    {
        en:'birthCountryValue',
        th:'ประเทศที่เกิด'
    },
    {
        en:'birthProvinceValue',
        th:'จังหวัดที่เกิด'
    },
    {
        en:'birthDistrictValue',
        th:'อำเภอที่เกิด'
    },
    {
        en:'birthSubDistricValue',
        th:'ตำบลที่เกิด'
    },
    {
        en:'houseNumber',
        th:'บ้านเลขที่ตามทะเบียนบ้าน'
    },
    {
        en:'village',
        th:'หมู่ที่ตามทะเบียนบ้าน'
    },
    {
        en:'road',
        th:'ถนนตามทะเบียนบ้าน'
    },
    {
        en:'countryValue',
        th:'ประเทศตามทะเบียนบ้าน'
    },
    {
        en:'provinceValue',
        th:'จังหวัดตามทะเบียนบ้าน'
    },
    {
        en:'districtValue',
        th:'อำเภอตามทะเบียนบ้าน'
    },
    {
        en:'subDistrictValue',
        th:'ตำบลตามทะเบียนบ้าน'
    },
    {
        en:'contractHouseNumber',
        th:'บ้านเลขที่ติดต่อ'
    },
    {
        en:'contractVillage',
        th:'หมู่ที่ติดต่อ'
    },
    {
        en:'contractRoad',
        th:'ถนนติดต่อ'
    },
    {
        en:'contractCountryValue',
        th:'ประเทศติดต่อ'
    },
    {
        en:'contractProvinceValue',
        th:'จังหวัดติดต่อ'
    },
    {
        en:'contractDistrictValue',
        th:'อำเภอติดต่อ'
    },
    {
        en:'contractSubDistrictValue',
        th:'ตำบลติดต่อ'
    },
    {
        en:'oldSchoolName',
        th:'ชื่อโรงเรียนเดิม'
    },
    {
        en:'oldSchoolCountryValue',
        th:'ประเทศโรงเรียนเดิม'
    },
    {
        en:'oldSchoolProvinceValue',
        th:'จังหวัดโรงเรียนเดิม'
    },
    {
        en:'oldSchoolDistrictValue',
        th:'อำเภอโรงเรียนเดิม'
    },
    {
        en:'oldSchoolSubDistrictValue',
        th:'ตำบลโรงเรียนเดิม'
    },
    {
        en:'closeFriendInClass',
        th:'ชื่อเพื่อนสนิทในชั้น'
    },
    {
        en:'closeFriendInClassNickname',
        th:'ชื่อเล่นเพื่อนสนิทในชั้น'
    },
    {
        en:'closeFriendInClassSchool',
        th:'โรงเรียนเพื่อนสนิทในชั้น'
    },
    {
        en:'closeFriendInClassPhone',
        th:'เบอร์โทรเพื่อนสนิทในชั้น'
    },
    {
        en:'closeFriendOtherClass',
        th:'ชื่อเพื่อนสนิทต่างชั้น'
    },
    {
        en:'closeFriendOtherClassNickname',
        th:'ชื่อเล่นเพื่อนสนิทต่างชั้น'
    },
    {
        en:'closeFriendOtherClassSchool',
        th:'โรงเรียนเพื่อนสนิทต่างชั้น'
    },
    {
        en:'closeFriendOtherClassPhone',
        th:'เบอร์โทรเพื่อนสนิทต่างชั้น'
    },
    {
        en:'bloodType',
        th:'หมู่เลือด'
    },
    {
        en:'congenitalDisease',
        th:'โรคประจำตัว'
    },
    {
        en:'height',
        th:'ส่วนสูง(เซนติเมตร)'
    },
    {
        en:'weight',
        th:'น้ําหนัก(กิโลกรัม)'
    },
    {
        en:'defect',
        th:'ข้อบกพร่อง'
    },
    {
        en:'aliveWithValue',
        th:'ปัจจุบันอาศัยอยู่กับ'
    },
    {
        en:'parentStatus',
        th:'สถานะผู้ปกครองปัจจุบัน'
    },
    {
        en:'fatherTitle',
        th:'คำนำหน้าบิดา'
    },
    {
        en:'fatherFirstname',
        th:'ชื่อบิดา'
    },
    {
        en:'fatherLastname',
        th:'นามสกุลบิดา'
    },
    {
        en:'fatherPersonalCode',
        th:'หมายเลขบัตรประชาชนบิดา'
    },
    {
        en:'fatherBloodType',
        th:'หมู่เลือดบิดา'
    },
    {
        en:'fatherIncome',
        th:'รายได้บิดา'
    },
    {
        en:'fatherOccupation',
        th:'อาชีพบิดา'
    },
    {
        en:'fatherPhone',
        th:'เบอร์โทรศัพท์บิดา'
    },
    {
        en:'motherTitle',
        th:'คำนำหน้ามารดา'
    },
    {
        en:'motherFirstname',
        th:'ชื่อมารดา'
    },
    {
        en:'motherLastname',
        th:'นามสกุลมารดา'
    },
    {
        en:'motherPersonalCode',
        th:'หมายเลขบัตรประชาชนมารดา'
    },
    {
        en:'motherBloodType',
        th:'หมู่เลือดมารดา'
    },
    {
        en:'motherIncome',
        th:'รายได้มารดา'
    },
    {
        en:'motherOccupation',
        th:'อาชีพมารดา'
    },
    {
        en:'motherPhone',
        th:'เบอร์โทรศัพท์มารดา'
    },
    {
        en:'parentTitle',
        th:'คำนำหน้าผู้ปกครอง'
    },
    {
        en:'parentFirstname',
        th:'ชื่อผู้ปกครอง'
    },
    {
        en:'parentLastname',
        th:'นามสกุลผู้ปกครอง'
    },
    {
        en:'parentPersonalCode',
        th:'หมายเลขบัตรประชาชนผู้ปกครอง'
    },
    {
        en:'parentBloodType',
        th:'หมู่เลือดผู้ปกครอง'
    },
    {
        en:'parentIncome',
        th:'รายได้ผู้ปกครอง'
    },
    {
        en:'parentOccupation',
        th:'อาชีพผู้ปกครอง'
    },
    {
        en:'parentPhone',
        th:'เบอร์โทรศัพท์ผู้ปกครอง'
    },
]
export const TEACHER_FIELD_NAME = [
    {
        en:'posonalCode',
        th:'เลขบัตรประชาชน'
    },
    {
        en:'status',
        th:'สถานะ'
    },
    {
        en:'ernlyDate',
        th:'วันที่ย้าย'
    },
    {
        en:'teacherCode',
        th:'เลขที่ตำแหน่ง'
    },
    {
        en:'title',
        th:'คำนำหน้า'
    },
    {
        en:'titleEn',
        th:'คำนำหน้า(EN)'
    },
    {
        en:'firstname',
        th:'ชื่อจริง'
    },
    {
        en:'lastname',
        th:'นามสกุล'
    },
    {
        en:'firstnameEn',
        th:'ชื่อจริง(EN)'
    },
    {
        en:'lastnameEn',
        th:'นามสกุล(EN)'
    },
    {
        en:'birthDate',
        th:'วันที่เกิด'
    },
 
    {
        en:'gendarValue',
        th:'เพศ'
    },

    {
        en:'nationalityValue',
        th:'สัญชาติ'
    },
    {
        en:'ethnicityValue',
        th:'เชื้อชาติ'
    },
    {
        en:'religionValue',
        th:'ศาสนา'
    },
    {
        en:'positionNumber',
        th:'เลขที่ตำแหน่ง'
    },
    {
        en:'positionName',
        th:'ตำแหน่ง'
    },
    {
        en:'practitionerLevelValue',
        th:'วิทยฐานะ'
    },
    {
        en:'practitionerNo',
        th:'อันดับ'
    },
    {
        en:'educationBackgroundValue',
        th:'ระดับการศึกษา'
    },
    {
        en:'otherEducationText',
        th:'ระดับการศึกษาอื่นๆ'
    },
    {
        en:'educationMajor',
        th:'สาขาวิชาเอก'
    },
    {
        en:'educationMinor',
        th:'วิชาโท'
    },
    {
        en:'setInDate',
        th:'วันที่เข้ารับราชการ'
    },
    {
        en:'setInDateSchool',
        th:'วันที่บรรจุเข้าในสถานศึกษา'
    },
    {
        en:'classroomTypeValue',
        th:'ประจำชั้น'
    },
    {
        en:'classroomValue',
        th:'ประจำห้อง'
    },
    {
        en:'teacherClass1',
        th:'ระดับชั้นที่สอนมัธยม1'
    },
    {
        en:'teacherClass2',
        th:'ระดับชั้นที่สอนมัธยม2'
    },
    {
        en:'teacherClass3',
        th:'ระดับชั้นที่สอนมัธยม3'
    },
    {
        en:'teacherClass4',
        th:'ระดับชั้นที่สอนมัธยม4'
    },
    {
        en:'teacherClass5',
        th:'ระดับชั้นที่สอนมัธยม5'
    },
    {
        en:'teacherClass6',
        th:'ระดับชั้นที่สอนมัธยม6'
    },

    {
        en:'subjectGroupValue',
        th:'สังกัดกลุ่มสาระ'
    },
    {
        en:'subjectGroupText',
        th:'สังกัดกลุ่มสาระอื่นๆ'
    },

    {
        en:'actionWork',
        th:'ปฎิบัติหน้าที่'
    },
    {
        en:'actionWorkSpecial',
        th:'หน้าที่พิเศษฝ่ายวิชาการ'
    },
    {
        en:'actionWorkSpecial2',
        th:'หน้าที่พิเศษฝ่ายอำนวยการ'
    },
    {
        en:'actionWorkSpecial3',
        th:'หน้าที่พิเศษฝ่ายกิจการนักเรียน'
    },
    {
        en:'actionWorkSpecial4',
        th:'หน้าที่พิเศษฝ่ายบริหารทั่วไป'
    },
    {
        en:'teacherEmail',
        th:'ที่อยู่อีเมลล์'
    },
    {
        en:'phoneNumber',
        th:'เบอร์โทรศัพท์'
    },
    {
        en:'houseNumber',
        th:'บ้านเลขที่'
    },
    {
        en:'village',
        th:'หมู่ที่'
    },
    {
        en:'road',
        th:'ถนน'
    },
    {
        en:'countryValue',
        th:'ประเทศ'
    },
    {
        en:'provinceValue',
        th:'จังหวัด'
    },
    {
        en:'districtValue',
        th:'อำเภอ'
    },
    {
        en:'subDistrictValue',
        th:'ตำบล'
    },
   

]