export class SarTeachingFormatListModel{
    id:number
    refId: string;
    schoolyear: string;
    teachingFormat1: boolean;
    teachingFormat2: boolean;
    teachingFormat3: boolean;
    teachingFormat4: boolean;
    teachingFormat5: boolean;
    teachingFormat6: boolean;
    teachingFormat7: boolean;
    teachingFormat8: boolean;
    teachingFormat9: boolean;
    teachingFormat10: boolean;
    teachingFormat11: boolean;
    teachingFormat12: boolean;
    teachingFormat13: boolean;
    teachingFormat14: boolean;
    teachingFormat15: boolean;
    teachingFormat16: boolean;
    teachingFormat17: boolean;
    teachingFormat18: boolean;
    teachingFormat19: boolean;
    teachingFormat20: boolean;
    teachingFormat21: boolean;
    teachingFormat22: boolean;
    teachingFormat23: boolean;
    teachingFormat24: boolean;
    teachingFormat25: boolean;
    teachingFormat26: boolean;
    teachingFormatOther: boolean;
    teachingFormatOtherNote: string;
    teacherId:number;
    teacherValue:string;
}
export class SarTeachingFormatItemModel{
    id:number
    refId: string;
    schoolyear: string;
    teachingFormat1: boolean;
    teachingFormat2: boolean;
    teachingFormat3: boolean;
    teachingFormat4: boolean;
    teachingFormat5: boolean;
    teachingFormat6: boolean;
    teachingFormat7: boolean;
    teachingFormat8: boolean;
    teachingFormat9: boolean;
    teachingFormat10: boolean;
    teachingFormat11: boolean;
    teachingFormat12: boolean;
    teachingFormat13: boolean;
    teachingFormat14: boolean;
    teachingFormat15: boolean;
    teachingFormat16: boolean;
    teachingFormat17: boolean;
    teachingFormat18: boolean;
    teachingFormat19: boolean;
    teachingFormat20: boolean;
    teachingFormat21: boolean;
    teachingFormat22: boolean;
    teachingFormat23: boolean;
    teachingFormat24: boolean;
    teachingFormat25: boolean;
    teachingFormat26: boolean;
    teachingFormatOther: boolean;
    teachingFormatOtherNote: string;
    teacherId:number;
    teacherValue:string;
}
