export class SarListModel{
    id:number
    teacherId: number;
    teacherValue: string;
    refId: string;
    schoolyear: string;
}
export class SarItemModel{
    id:number
    teacherId: number;
    teacherValue: string;
    refId: string;
    schoolyear: string;
    firstname: string;
    lastname: string;
    schoolYear: string;
    leaveDate: Date;
    totalLeaveTimes: number;
    totalLeaveDays: number;
    sickLeaveTimes: number;
    sickLeaveDays: number;
    businessLeaveTimes: number;
    businessLeaveDays: number;
    ordinationLeaveTimes: number;
    ordinationLeaveDays: number;
    deliverLeaveTimes: number;
    deliverLeaveDays: number;
    lateTimes: number;
    lateLeaveDays: number;
    totalSickLeaveTimes: number;
    totalSickLeaveDays: number;
    totalBusinessLeaveTimes: number;
    totalBusinessLeaveDays: number;
    totalOrdinationLeaveTimes: number;
    totalOrdinationLeaveDays: number;
    totalDeliverLeaveTimes: number;
    totalDeliverLeaveDays: number;
    totalLateTimes: number;
    totalLateLeaveDays: number;
    education:any;
    practitionerLevelNameValue: string;
    positionName: string;
    age: string;
    setInTotalYear: string;
    birthDate: Date;
    setInDate: Date;
    subjectGroupValue: string;
    actionWorkSpecial: string;
    subjectGroupId: number;
  
    positionNumber: string;
    salary: string;
    practitionerMoney: string;
    affiliation: string;
    birthDateValue: string;
    setInDateValue: string;
    sarPersonalLeaveDataTitle: string;

sum_sickLeaveTimes : number;
 sum_sickLeaveDays : number;
 sum_businessLeaveTimes : number;
 sum_businessLeaveDays : number;
 sum_ordinationLeaveTimes : number;
 sum_ordinationLeaveDays : number;
 sum_deliverLeaveTimes : number;
 sum_deliverLeaveDays : number;
 sum_lateTimes : number;
 sum_lateLeaveDays : number;
 total_times: number;
 total_days: number;
 sarCoursesYearTermTitle : string;
 sarCoursesYearTerm2Title : string;
 teachingscheduleTerm1Model:{
    teacherId: number;
    teacherValue: string;
    yearTermId: number;
    yearTermValue: string;
    monSubjectName01: string;
    monSubjectName02: string;
    monSubjectName03: string;
    monSubjectName04: string;
    monSubjectName05: string;
    monSubjectName06: string;
    monSubjectName07: string;
    monSubjectName08: string;
    monSubjectName09: string;
    monSubjectName10: string;
    monSubjectId01: string;
    monSubjectId02: string;
    monSubjectId03: string;
    monSubjectId04: string;
    monSubjectId05: string;
    monSubjectId06: string;
    monSubjectId07: string;
    monSubjectId08: string;
    monSubjectId09: string;
    monSubjectId10: string;
    monClass01: string;
    monClass02: string;
    monClass03: string;
    monClass04: string;
    monClass05: string;
    monClass06: string;
    monClass07: string;
    monClass08: string;
    monClass09: string;
    monClass10: string;
    tueSubjectName01: string;
    tueSubjectName02: string;
    tueSubjectName03: string;
    tueSubjectName04: string;
    tueSubjectName05: string;
    tueSubjectName06: string;
    tueSubjectName07: string;
    tueSubjectName08: string;
    tueSubjectName09: string;
    tueSubjectName10: string;
    tueSubjectId01: string;
    tueSubjectId02: string;
    tueSubjectId03: string;
    tueSubjectId04: string;
    tueSubjectId05: string;
    tueSubjectId06: string;
    tueSubjectId07: string;
    tueSubjectId08: string;
    tueSubjectId09: string;
    tueSubjectId10: string;
    tueClass01: string;
    tueClass02: string;
    tueClass03: string;
    tueClass04: string;
    tueClass05: string;
    tueClass06: string;
    tueClass07: string;
    tueClass08: string;
    tueClass09: string;
    tueClass10: string;
    wedSubjectName01: string;
    wedSubjectName02: string;
    wedSubjectName03: string;
    wedSubjectName04: string;
    wedSubjectName05: string;
    wedSubjectName06: string;
    wedSubjectName07: string;
    wedSubjectName08: string;
    wedSubjectName09: string;
    wedSubjectName10: string;
    wedSubjectId01: string;
    wedSubjectId02: string;
    wedSubjectId03: string;
    wedSubjectId04: string;
    wedSubjectId05: string;
    wedSubjectId06: string;
    wedSubjectId07: string;
    wedSubjectId08: string;
    wedSubjectId09: string;
    wedSubjectId10: string;
    wedClass01: string;
    wedClass02: string;
    wedClass03: string;
    wedClass04: string;
    wedClass05: string;
    wedClass06: string;
    wedClass07: string;
    wedClass08: string;
    wedClass09: string;
    wedClass10: string;
    thursSubjectName01: string;
    thursSubjectName02: string;
    thursSubjectName03: string;
    thursSubjectName04: string;
    thursSubjectName05: string;
    thursSubjectName06: string;
    thursSubjectName07: string;
    thursSubjectName08: string;
    thursSubjectName09: string;
    thursSubjectName10: string;
    thursSubjectId01: string;
    thursSubjectId02: string;
    thursSubjectId03: string;
    thursSubjectId04: string;
    thursSubjectId05: string;
    thursSubjectId06: string;
    thursSubjectId07: string;
    thursSubjectId08: string;
    thursSubjectId09: string;
    thursSubjectId10: string;
    thursClass01: string;
    thursClass02: string;
    thursClass03: string;
    thursClass04: string;
    thursClass05: string;
    thursClass06: string;
    thursClass07: string;
    thursClass08: string;
    thursClass09: string;
    thursClass10: string;
    firSubjectName01: string;
    firSubjectName02: string;
    firSubjectName03: string;
    firSubjectName04: string;
    firSubjectName05: string;
    firSubjectName06: string;
    firSubjectName07: string;
    firSubjectName08: string;
    firSubjectName09: string;
    firSubjectName10: string;
    firSubjectId01: string;
    firSubjectId02: string;
    firSubjectId03: string;
    firSubjectId04: string;
    firSubjectId05: string;
    firSubjectId06: string;
    firSubjectId07: string;
    firSubjectId08: string;
    firSubjectId09: string;
    firSubjectId10: string;
    firClass01: string;
    firClass02: string;
    firClass03: string;
    firClass04: string;
    firClass05: string;
    firClass06: string;
    firClass07: string;
    firClass08: string;
    firClass09: string;
    firClass10: string;
    year_term_id:number;
    year:string;
    term:string;
    teacher_title:number;
    teacher_firstname:string;
    teacher_lastname:string;
    schoolYear: string;
    refId: string;
 }
 teachingscheduleTerm2Model:{
    teacherId: number;
    teacherValue: string;
    yearTermId: number;
    yearTermValue: string;
    monSubjectName01: string;
    monSubjectName02: string;
    monSubjectName03: string;
    monSubjectName04: string;
    monSubjectName05: string;
    monSubjectName06: string;
    monSubjectName07: string;
    monSubjectName08: string;
    monSubjectName09: string;
    monSubjectName10: string;
    monSubjectId01: string;
    monSubjectId02: string;
    monSubjectId03: string;
    monSubjectId04: string;
    monSubjectId05: string;
    monSubjectId06: string;
    monSubjectId07: string;
    monSubjectId08: string;
    monSubjectId09: string;
    monSubjectId10: string;
    monClass01: string;
    monClass02: string;
    monClass03: string;
    monClass04: string;
    monClass05: string;
    monClass06: string;
    monClass07: string;
    monClass08: string;
    monClass09: string;
    monClass10: string;
    tueSubjectName01: string;
    tueSubjectName02: string;
    tueSubjectName03: string;
    tueSubjectName04: string;
    tueSubjectName05: string;
    tueSubjectName06: string;
    tueSubjectName07: string;
    tueSubjectName08: string;
    tueSubjectName09: string;
    tueSubjectName10: string;
    tueSubjectId01: string;
    tueSubjectId02: string;
    tueSubjectId03: string;
    tueSubjectId04: string;
    tueSubjectId05: string;
    tueSubjectId06: string;
    tueSubjectId07: string;
    tueSubjectId08: string;
    tueSubjectId09: string;
    tueSubjectId10: string;
    tueClass01: string;
    tueClass02: string;
    tueClass03: string;
    tueClass04: string;
    tueClass05: string;
    tueClass06: string;
    tueClass07: string;
    tueClass08: string;
    tueClass09: string;
    tueClass10: string;
    wedSubjectName01: string;
    wedSubjectName02: string;
    wedSubjectName03: string;
    wedSubjectName04: string;
    wedSubjectName05: string;
    wedSubjectName06: string;
    wedSubjectName07: string;
    wedSubjectName08: string;
    wedSubjectName09: string;
    wedSubjectName10: string;
    wedSubjectId01: string;
    wedSubjectId02: string;
    wedSubjectId03: string;
    wedSubjectId04: string;
    wedSubjectId05: string;
    wedSubjectId06: string;
    wedSubjectId07: string;
    wedSubjectId08: string;
    wedSubjectId09: string;
    wedSubjectId10: string;
    wedClass01: string;
    wedClass02: string;
    wedClass03: string;
    wedClass04: string;
    wedClass05: string;
    wedClass06: string;
    wedClass07: string;
    wedClass08: string;
    wedClass09: string;
    wedClass10: string;
    thursSubjectName01: string;
    thursSubjectName02: string;
    thursSubjectName03: string;
    thursSubjectName04: string;
    thursSubjectName05: string;
    thursSubjectName06: string;
    thursSubjectName07: string;
    thursSubjectName08: string;
    thursSubjectName09: string;
    thursSubjectName10: string;
    thursSubjectId01: string;
    thursSubjectId02: string;
    thursSubjectId03: string;
    thursSubjectId04: string;
    thursSubjectId05: string;
    thursSubjectId06: string;
    thursSubjectId07: string;
    thursSubjectId08: string;
    thursSubjectId09: string;
    thursSubjectId10: string;
    thursClass01: string;
    thursClass02: string;
    thursClass03: string;
    thursClass04: string;
    thursClass05: string;
    thursClass06: string;
    thursClass07: string;
    thursClass08: string;
    thursClass09: string;
    thursClass10: string;
    firSubjectName01: string;
    firSubjectName02: string;
    firSubjectName03: string;
    firSubjectName04: string;
    firSubjectName05: string;
    firSubjectName06: string;
    firSubjectName07: string;
    firSubjectName08: string;
    firSubjectName09: string;
    firSubjectName10: string;
    firSubjectId01: string;
    firSubjectId02: string;
    firSubjectId03: string;
    firSubjectId04: string;
    firSubjectId05: string;
    firSubjectId06: string;
    firSubjectId07: string;
    firSubjectId08: string;
    firSubjectId09: string;
    firSubjectId10: string;
    firClass01: string;
    firClass02: string;
    firClass03: string;
    firClass04: string;
    firClass05: string;
    firClass06: string;
    firClass07: string;
    firClass08: string;
    firClass09: string;
    firClass10: string;
    year_term_id:number;
    year:string;
    term:string;
    teacher_title:number;
    teacher_firstname:string;
    teacher_lastname:string;
    schoolYear: string;
    refId: string;
 }
 sarAnotherSpeacialDutyTitle: string;

 sarTeachingFormatModel:{
    teachingFormat1: boolean;
    teachingFormat2: boolean;
    teachingFormat3: boolean;
    teachingFormat4: boolean;
    teachingFormat5: boolean;
    teachingFormat6: boolean;
    teachingFormat7: boolean;
    teachingFormat8: boolean;
    teachingFormat9: boolean;
    teachingFormat10: boolean;
    teachingFormat11: boolean;
    teachingFormat12: boolean;
    teachingFormat13: boolean;
    teachingFormat14: boolean;
    teachingFormat15: boolean;
    teachingFormat16: boolean;
    teachingFormat17: boolean;
    teachingFormat18: boolean;
    teachingFormat19: boolean;
    teachingFormat20: boolean;
    teachingFormat21: boolean;
    teachingFormat22: boolean;
    teachingFormat23: boolean;
    teachingFormat24: boolean;
    teachingFormat25: boolean;
    teachingFormat26: boolean;
    teachingFormatOther: boolean;
    teachingFormatOtherNote: string;

 }
 sarTeachingConditionModel:{
    choice1: number;
    choice2: number;
    choice3: number;
    choice4: number;
    choice5: number;
 }
 sarperformingspecialdutiesModel:{
    group1Text1: string;
    group1Text2: string;
    group1Text3: string;
    group1Result: number;
    group2Text1: string;
    group2Text2: string;
    group2Text3: string;
    group2Text4: string;
    group2Text5: string;
    group2Result: number;
    group3Text1: string;
    group3Text2: string;
    group3Result: number;
    group4Text1: string;
    group4Text2: string;
    group4Result: number;
    group4Text3: string;

    
    group1Text4: string;
    group1Text5: string;
    group5Text1: string;
    group5Text2: string;
    group5Result: number;
 }
 sarstudentestimateteachingModel:{
   choice1_5P: number;
    choice1_4P: number;
    choice1_3P: number;
    choice1_2P: number;
    choice1_1P: number;

    choice2_5P: number;
    choice3_5P: number;
    choice4_5P: number;
    choice5_5P: number;
    choice6_5P: number;
    choice7_5P: number;
    choice8_5P: number;
    choice9_5P: number;
    choice10_5P: number;
    choice11_5P: number;
    choice12_5P: number;
    choice13_5P: number;
    choice14_5P: number;
    choice15_5P: number;
    choice16_5P: number;
    choice17_5P: number;
    choice18_5P: number;
    choice19_5P: number;
    choice20_5P: number;

    choice2_4P: number;
    choice3_4P: number;
    choice4_4P: number;
    choice5_4P: number;
    choice6_4P: number;
    choice7_4P: number;
    choice8_4P: number;
    choice9_4P: number;
    choice10_4P: number;
    choice11_4P: number;
    choice12_4P: number;
    choice13_4P: number;
    choice14_4P: number;
    choice15_4P: number;
    choice16_4P: number;
    choice17_4P: number;
    choice18_4P: number;
    choice19_4P: number;
    choice20_4P: number;

    choice2_3P: number;
    choice3_3P: number;
    choice4_3P: number;
    choice5_3P: number;
    choice6_3P: number;
    choice7_3P: number;
    choice8_3P: number;
    choice9_3P: number;
    choice10_3P: number;
    choice11_3P: number;
    choice12_3P: number;
    choice13_3P: number;
    choice14_3P: number;
    choice15_3P: number;
    choice16_3P: number;
    choice17_3P: number;
    choice18_3P: number;
    choice19_3P: number;
    choice20_3P: number;

    choice2_2P: number;
    choice3_2P: number;
    choice4_2P: number;
    choice5_2P: number;
    choice6_2P: number;
    choice7_2P: number;
    choice8_2P: number;
    choice9_2P: number;
    choice10_2P: number;
    choice11_2P: number;
    choice12_2P: number;
    choice13_2P: number;
    choice14_2P: number;
    choice15_2P: number;
    choice16_2P: number;
    choice17_2P: number;
    choice18_2P: number;
    choice19_2P: number;
    choice20_2P: number;

    choice2_1P: number;
    choice3_1P: number;
    choice4_1P: number;
    choice5_1P: number;
    choice6_1P: number;
    choice7_1P: number;
    choice8_1P: number;
    choice9_1P: number;
    choice10_1P: number;
    choice11_1P: number;
    choice12_1P: number;
    choice13_1P: number;
    choice14_1P: number;
    choice15_1P: number;
    choice16_1P: number;
    choice17_1P: number;
    choice18_1P: number;
    choice19_1P: number;
    choice20_1P: number;
    result: number;
}

 

 sarselfassessmentModel:{
    choice1: number;
    choice2: number;
    choice3: number;
    choice4: number;
    choice5: number;
    result: string;
 }
 sarqualityoflearnersModel:{
    choice1: number;
    choice2: number;
    choice3: number;
    choice4: number;
    choice5: number;
    choice6: number;
    choice7: number;
    choice8: number;
    choice9: number;
    choice10: number;
    choice11: number;
    choice12: number;
    choice13: number;
    choice14: number;
    choice15: number;
    choice16: number;
    result: number;
 }

 sarstandard2Model:{
    choice1: number;
    choice2: number;
    choice3: number;
    choice4: number;
    choice5: number;
    choice6: number;
    choice7: number;
    result: number;
 }
 sarstandard3Model:{
    choice1: number;
    choice2: number;
    choice3: number;
    choice4: number;
    choice5: number;
    choice6: number;
    choice7: number;
    choice8: number;
    choice9: number;
    choice10: number;
    choice11: number;
    choice12: number;
    result: number;
 }
 sarstandard4Model:{
    choice1: number;
    choice2: number;
    choice3: number;
    result: number;
 }
 sacompetencyassessmentresult:string;
 sarcrudassessmentresult:string;
 sarCoursesYearTermSumHour:number;
 sarCoursesYearTermSumTotalRoom:number;
 sarCoursesYearTerm2TotalRoom:number;
 sarCoursesYearTermToTalSubject:number;
 sarCoursesYearTermToTalActivities:number;
 sarCoursesYearTermToTalHour:number;
 sarCoursesYearTerm2ToTalSubject:number;
 sarCoursesYearTerm2ToTalActivities:number;
 sarCoursesYearTerm2ToTalHour:number;
 sarCoursesYearTerm2SumHour:number;
 sarMediaProductionTotal:number;
 sarResearchInClassTotal:number;
 sarTeachingFormatTotal:number;
 
 sarselfdevelopmentToTalTimes:number;
 sarselfdevelopmentToTaldays:number;
 sarselfdevelopmentToTalHour:number;
 sarselfdevelopmentToTalTimes2:number;
 sarattributeassessmentresult:string;
 //รวม เทอม1
 teachingresulttotalStudent_01:number;
 teachingresultresultGrad2_01:number;
 teachingresultresultGrad1_01:number;
 teachingresultresultGrad3_01:number;
 teachingresultresultGrad4_01:number;
 teachingresultresultGrad5_01:number;
 teachingresultresultGrad6_01:number;
 teachingresultresultGrad7_01:number;
 teachingresultresultGrad8_01:number;
 teachingresultresultGrad9_01:number;
 teachingresultresultGrad10_01:number;
 teachingresulttotalResultGrad_01:number;
 //รวม เทอม2
 teachingresulttotalStudent_02:number;
 teachingresultresultGrad2_02:number;
 teachingresultresultGrad1_02:number;
 teachingresultresultGrad3_02:number;
 teachingresultresultGrad4_02:number;
 teachingresultresultGrad5_02:number;
 teachingresultresultGrad6_02:number;
 teachingresultresultGrad7_02:number;
 teachingresultresultGrad8_02:number;
 teachingresultresultGrad9_02:number;
 teachingresultresultGrad10_02:number;
 teachingresulttotalResultGrad_02:number;
 //รวม2เทอม
 teachingresulttotalStudent:number;
 teachingresultresultGrad2:number;
 teachingresultresultGrad1:number;
 teachingresultresultGrad3:number;
 teachingresultresultGrad4:number;
 teachingresultresultGrad5:number;
 teachingresultresultGrad6:number;
 teachingresultresultGrad7:number;
 teachingresultresultGrad8:number;
 teachingresultresultGrad9:number;
 teachingresultresultGrad10:number;
 teachingresulttotalResultGrad:number;
//
 teachingresultresultGrad2Persent:string;
 teachingresultresultGrad1Persent:string;
 teachingresultresultGrad3Persent:string;
 teachingresultresultGrad4Persent:string;
 teachingresultresultGrad5Persent:string;
 teachingresultresultGrad6Persent:string;
 teachingresultresultGrad7Persent:string;
 teachingresultresultGrad8Persent:string;
 teachingresultresultGrad9Persent:string;
 teachingresultresultGrad10Persent:string;
 teachingresulttotalResultGradPersent:string;

 teachingresulttotalMoreGrad2:number;
 teachingresulttotalMoreGrad3:number;
 teachingresulttotalMoreGrad2Persent:string;
 teachingresulttotalMoreGrad3Persent:string;
 title:number;
 sarPersonalLeaveschoolYearValue:string;

 sarqualityoflearners_total_P5: number;
 sarqualityoflearners_total_P4: number;
 sarqualityoflearners_total_P3: number;
 sarqualityoflearners_total_P2: number;
 sarqualityoflearners_total_P1: number;
 sarqualityoflearners_total_result: number;
 sarqualityoflearners_total_result_value: string;
 sarstandard2_total_P5: number;
 sarstandard2_total_P4: number;
 sarstandard2_total_P3: number;
 sarstandard2_total_P2: number;
 sarstandard2_total_P1: number;
 sarstandard2_total_result: number;
 sarstandard2_total_result_value: string;
 sarstandard3_total_P5: number;
 sarstandard3_total_P4: number;
 sarstandard3_total_P3: number;
 sarstandard3_total_P2: number;
 sarstandard3_total_P1: number;
 sarstandard3_total_result: number;
 sarstandard3_total_result_value: string;

sarcrudassessmentTerm1_assessment1: number;
sarcrudassessmentTerm1_assessment2: number;
sarcrudassessmentTerm1_assessment3: number;
sarcrudassessmentTerm1_assessment4: number;
sarcrudassessmentTerm1_totalStudent: number;
sarcrudassessmentTerm1_assessment1_persent: string;
sarcrudassessmentTerm1_assessment2_persent: string;
sarcrudassessmentTerm1_assessment3_persent: string;
sarcrudassessmentTerm1_assessment4_persent: string;

sarcrudassessmentTerm2_assessment1: number;
sarcrudassessmentTerm2_assessment2: number;
sarcrudassessmentTerm2_assessment3: number;
sarcrudassessmentTerm2_assessment4: number;
sarcrudassessmentTerm2_totalStudent: number;
sarcrudassessmentTerm2_assessment1_persent: string;
sarcrudassessmentTerm2_assessment2_persent: string;
sarcrudassessmentTerm2_assessment3_persent: string;
sarcrudassessmentTerm2_assessment4_persent: string;

sacompetencyassessmentTerm1_assessment1: number;
sacompetencyassessmentTerm1_assessment2: number;
sacompetencyassessmentTerm1_assessment3: number;
sacompetencyassessmentTerm1_assessment4: number;
sacompetencyassessmentTerm1_totalStudent: number;
sacompetencyassessmentTerm1_assessment1_persent: string;
sacompetencyassessmentTerm1_assessment2_persent: string;
sacompetencyassessmentTerm1_assessment3_persent: string;
sacompetencyassessmentTerm1_assessment4_persent: string;

sacompetencyassessmentTerm2_assessment1: number;
sacompetencyassessmentTerm2_assessment2: number;
sacompetencyassessmentTerm2_assessment3: number;
sacompetencyassessmentTerm2_assessment4: number;
sacompetencyassessmentTerm2_totalStudent: number;
sacompetencyassessmentTerm2_assessment1_persent: string;
sacompetencyassessmentTerm2_assessment2_persent: string;
sacompetencyassessmentTerm2_assessment3_persent: string;
sacompetencyassessmentTerm2_assessment4_persent: string;

//ฟกก แนสีทื
 sarqualityoflearnersNote:string;
 sarstandard2Note:string;
 sarstandard3Note:string;
 SelfAssessment1_1:string;
 SelfAssessment1_2:string;
 SelfAssessment1_3:string;
 SelfAssessment2_1:string;
 SelfAssessment2_2:string;
 SelfAssessment2_3:string;
 SelfAssessment3_1:string;
 SelfAssessment3_2:string;
 SelfAssessment3_3:string;
 SelfAssessment4_1:string;
 SelfAssessment4_2:string;
 SelfAssessment4_3:string;
 
}
